name: AutoML with TPOT
description: Automated data visualization and scikit learn pipeline creation using TPOT, Dask, and CML Workers in a jupyter notebook.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-04-12"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.9
    edition: Standard
    version: 2021.09

tasks:
  - type: create_job
    name: Install Dependencies
    entity_label: install_dependencies
    script: cml/install_dependencies.py
    arguments: None
    cpu: 2
    memory: 4
    short_summary: Create job to install project dependencies.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_dependencies
    short_summary: Running install dependencies job.
    long_summary: Running the job to install dependencies.
